routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PagesController@index')->name('index');
Route::get('news/{NewsModel}', 'PagesController@show')->name('news.show');

Auth::routes();

Route::group(['prefix'=>'admin', 'namespace'=>'Admin', 'middleware'=>['auth']], function() {
  Route::group(['as' => 'admin.'], function() {
    Route::get('home', 'HomeController@index')->name('home');
    Route::resource('newsModels', 'NewsModelsController');
  });
});

app/NewsModel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class NewsModel extends Model
{
  protected $fillable = [
    'title', 'body', 'image_src'
  ];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Admin/HomeController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.home');
    }
}

app/Http/Controllers/Admin/NewsModelsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\NewsModel;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\File;
use Illuminate\Http\UploadedFile;

class NewsModelsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $news = NewsModel::all();
      return view('admin.news.index', compact('news'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      return view('admin.news.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $this->validate($request, [
        'title' => 'required|string|max:255',
        'body' => 'required',
        'image_src' => 'required|image',
      ]);
      $image = $request->file('image_src');
      $new_name = date('Y-m-d-H-i-s') . '.' . $image->getClientOriginalExtension();
      $image->move(public_path() . '\img', $new_name);

      NewsModel::create([
        'title' => $request['title'],
        'body' => $request['body'],
        'image_src' => $new_name,
      ]);
      return redirect()->route('admin.newsModels.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\NewsModel  $newsModel
     * @return \Illuminate\Http\Response
     */
    public function show(NewsModel $newsModel)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\NewsModel  $newsModel
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, NewsModel $newsModel)
    {
      $entity = $newsModel;
      return view('admin.news.form', compact('entity'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\NewsModel  $newsModel
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, NewsModel $newsModel)
    {
      $this->validate($request, [
        'title' => 'required|string|max:255',
        'image_src' => 'image',
      ]);
      
      $new_name = $newsModel['image_src'];

      if (!empty($request['image_src'])) {
        $image = $request->file('image_src');
        $new_name = date('Y-m-d-H-i-s') . '.' . $image->getClientOriginalExtension();
        $image->move(public_path() . '\img', $new_name);
      }

      $newsModel->update([
        'title' => $request['title'],
        'body' => $request['body'],
        'image_src' => $new_name,
      ]);
      return redirect()->route('admin.newsModels.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\NewsModel  $newsModel
     * @return \Illuminate\Http\Response
     */
    public function destroy(NewsModel $newsModel)
    {
      $newsModel->delete();
      return redirect()->route('admin.newsModels.index');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PagesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\NewsModel;


class PagesController extends Controller
{
    public function index(Request $request)
    {
      $news = NewsModel::limit(10)->get();
      return view('index', ['news' => $news]);
    }

    public function show(NewsModel $NewsModel) {
      return view('show', ['news' => $NewsModel]);
    }

}

resources/views/admin/fields/image.blade.php
@extends('admin.fields.main')

@section('field')
	@if(isset($entity->$field) && !empty($entity->$field))
		<img src="{{ '\img\\' . $entity->$field }}" class="img-thumbnail" width="304" height="236">
	@endif
	<div class="btn btn-default btn-file">
		{{ Form::file($field) }}
	</div>

@overwrite

resources/views/admin/fields/label.blade.php
@extends('admin.layout.fields.main')

@section('field')
	{{ $entity->$field }}
@overwrite

resources/views/admin/fields/main.blade.php
<div class="form-group row @if($errors->get($field)) has-error @endif">
	<label for="{{ $field }}" class="col-sm-3 col-form-label">{{ $name }}</label>
	<div class="col-sm-9">
		<span class="warning">
			@foreach ($errors->get($field) as $message)
				{!! $message !!}
			@endforeach
		</span>
	@yield('field')
	</div>
</div>

resources/views/admin/fields/text.blade.php
@extends('admin.fields.main')

@section('field')
	<input type="{{ isset($type) ? $type : 'text' }}" name="{{ $field }}" value="{{ isset($isEmpty) ? '' : old($field, (isset($entity) ? $entity->$field : '')) }}" class="form-control">
@overwrite

resources/views/admin/fields/textarea.blade.php
@extends('admin.fields.main')

@section('field')
	<textarea rows="{{ isset($rows) ? $rows : 5 }}" name="{{ $field }}" class="form-control">{{ old($field, (isset($entity) ? $entity->$field : '')) }}</textarea>
@overwrite

resources/views/admin/home.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav">
                      <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">News</a>
                        <div class="dropdown-menu">
                          <a class="dropdown-item" href="{{ route('admin.newsModels.index') }}">List</a>
                          <a class="dropdown-item" href="{{ route('admin.newsModels.create') }}">New</a>
                        </div>
                      </li>
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->username }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>
                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>

                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>
        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/admin/news/form.blade.php
@extends('admin.layouts.app')

@section('content')
	<div class="container">
		<div class="row">
			<div class="col-md-8">
				<div class="card">
					<div class="card-body">
					@if(empty($entity))
						<div class="card-title">Create news</div>
					@else
						<div class="card-title">Edit news</div>
					@endif
						<form action="@if(empty($entity)){{ route('admin.newsModels.store') }}@else{{ route('admin.newsModels.update', $entity->id) }}@endif" method="POST" enctype="multipart/form-data">
							{{ csrf_field() }}
							@isset($entity)
								 {{ method_field('PUT') }}
							@endisset
								@include('admin.fields.text', ['type'=>'text', 'field' => 'title', 'name' => 'Title'])
                @include('admin.fields.textarea', ['field' => 'body', 'name' => 'Body', 'rows' => 10])
                @include('admin.fields.image', ['field' => 'image_src', 'name' => 'Image'])
							<input class="btn btn-primary" type="submit" value="Save">
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection

resources/views/admin/news/index.blade.php
@extends('admin.layouts.app')

@section('content')
  <div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="card">
					<div class="card-body">
					<div class="card-title">News</div>
						@if($news->count() > 0)
							<table class="table">
								<tr>
									<th>ID</th>
									<th>Title</th>
									<th>Body</th>
									<th>Image</th>
									<th>Action</th>
								</tr>
								@foreach($news as $newsItem)
									<tr>
										<td>{{ $newsItem->id }}</td>
										<td>{{ $newsItem->title }}</td>
										<td>{{ $newsItem->body }}</td>
                    <td>
                      <img class="table__image" src="\img\{{ $newsItem->image_src }}" alt="">
                    </td>
										<td>
											<form action="{{ route('admin.newsModels.destroy', $newsItem->id) }}" method="POST">
												{{ csrf_field() }}
                        {{ method_field('delete') }}
												<a  type="button" class="btn btn-primary" href="{{ route('admin.newsModels.edit', $newsItem->id) }}">Change news</a>
												<button type="submit" class="btn btn-danger">Delete</button>
											</form>
										</td>
									</tr>
								@endforeach
							</table>
						@else
							No news
						@endif
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection

resources/views/index.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="card">
					<div class="card-body">
					<div class="card-title">News</div>
						@if($news->count() > 0)
							<table class="table">
								<tr>
									<th>ID</th>
									<th>Title</th>
									<th>Body</th>
									<th>Image</th>
									<th>Action</th>
								</tr>
								@foreach($news as $newsItem)
									<tr>
										<td>{{ $newsItem->id }}</td>
										<td>{{ $newsItem->title }}</td>
										<td>{{ $newsItem->body }}</td>
                    <td>
                      <img class="table__image" src="\img\{{ $newsItem->image_src }}" alt="">
                    </td>
										<td>
                      <a  type="button" class="btn btn-primary" href="{{ route('news.show', $newsItem->id) }}">Open news</a>
										</td>
									</tr>
								@endforeach
							</table>
						@else
							No news
						@endif
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            <li class="nav-item">
                                @if (Route::has('register'))
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                @endif
                            </li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('admin.home') }}">Home</a>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/show.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="card">
					<div class="card-body">
					<div class="card-title">News</div>
							<table class="table">
								<tr>
									<th>ID</th>
									<th>Title</th>
									<th>Body</th>
									<th>Image</th>
								</tr>
									<tr>
										<td>{{ $news->id }}</td>
										<td>{{ $news->title }}</td>
										<td>{{ $news->body }}</td>
                    <td>
                      <img class="table__image" src="\img\{{ $news->image_src }}" alt="">
                    </td>
									</tr>
							</table>
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection